<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Retailer.Shared</RootNamespace>
        <AssemblyName>Retailer.Shared</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="NSwag.CodeGeneration.TypeScript" Version="14.6.3" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="Roslynator.Analyzers" Version="4.2.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Notifications\" />
    </ItemGroup>
</Project>