image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  branches:
    release/dev:
      - step:
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet build --no-restore
          artifacts:
            - bin/**
            - TestResults/**
      - step:
          name: Publish and Deploy to Azure
          deployment: Development
          caches:
            - dotnetcore
          script:
            # Skip if commit contains '--skip'
            - if git log -1 --pretty=%B | grep -q -- '--skip'; then echo "Skipping deployment due to '--skip' in commit message."; exit 0; fi

            # Notify: Deployment starting
            - '[ -n "$GCHAT_WEBHOOK_URL" ] && curl -X POST -H "Content-Type: application/json" -d "{\"text\":\"🚀 Deployment started \n\n📦 Project: $BITBUCKET_REPO_SLUG\n🌍 Environment: $BITBUCKET_DEPLOYMENT_ENVIRONMENT\"}" "$GCHAT_WEBHOOK_URL"'


            - echo "AZURE_CLIENT_ID=$AZURE_CLIENT_ID"
            - echo "AZURE_CLIENT_SECRET is set? ${AZURE_CLIENT_SECRET:+yes}"
            - echo "AZURE_TENANT_ID=$AZURE_TENANT_ID"

            # Publish output
            - dotnet publish ./src/Host/WebAPI/WebAPI.csproj -c Release -o ./publish

            # Zip published output
            - apt-get update && apt-get install -y zip curl
            - cd publish && zip -r ../app.zip . && cd ..

            # Install Azure CLI
            - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

            # Login to Azure using Service Principal
            - az login --service-principal --username "$AZURE_CLIENT_ID"  --password "$AZURE_CLIENT_SECRET"  --tenant "$AZURE_TENANT_ID"

            # Set subscription
            - az account set --subscription "$AZURE_SUBSCRIPTION_ID"

            # Deploy to Azure App Service
            - az webapp deployment source config-zip  --resource-group "$AZURE_RG_NAME"  --name "$AZURE_WEBAPP_NAME"  --src "app.zip"

            # Notify: Deployment successful
            - '[ -n "$GCHAT_WEBHOOK_URL" ] && curl -X POST -H "Content-Type: application/json" -d "{\"text\":\"✅ Deployment successful \n\n📦 Project: $BITBUCKET_REPO_SLUG\n🌍 Environment: $BITBUCKET_DEPLOYMENT_ENVIRONMENT \n\n🔖 Release Notes:\n$(git log -1 --pretty=%B) \"}" "$GCHAT_WEBHOOK_URL"'


          artifacts:
            - app.zip

  pull-requests:
    '**':
      - step:
          name: PR Build and Test
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet build --no-restore
          artifacts:
            - bin/**
            - TestResults/**

definitions:
  caches:
    dotnetcore: ~/.nuget/packages